name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Check Makefile syntax
      run: make -n all

    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Run shellcheck on shell scripts
      run: shellcheck *.sh

    - name: make all
      run: sudo make all
