name: Makefile CI

on:
  push:
    branches: [ "master", "wip" ]
  pull_request:
    branches: [ "master", "wip" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Check Makefile syntax
      run: make -n all

    - name: Install shellcheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Run shellcheck on shell scripts
      run: shellcheck *.sh

    - name: make all
      run:
        set -euo pipefail
        echo "Running install as root to loosely simulate termux environment..."
        sudo make -j"$(nproc)" all

    - name: setup for backup test
      run:
        set -euo pipefail
        sudo HOME="$HOME" bash -c 'mkdir -p "$HOME/bin"&&echo test > "$HOME/bin/termux-url-opener"&&cp "$HOME/bin/termux-url-opener" "$HOME/bin/termux-url-opener~"&&chmod +x "$HOME/bin/termux-file-editor"&&ln -sfb "$HOME/bin/termux-url-opener" "$HOME/bin/termux-file-editor"'
        ls -l ~/bin
        
    - name: run install script directly
      run:
        set -euo pipefail
        echo 'Running again to check backup function'
        sudo HOME="$HOME" bash -x ./install.sh
      
    - name: check if ~/bin/termux-url-opener~ exists
      run:
        ls -l ~/bin
        test -e "$HOME/bin/termux-url-opener~"
